### ISSUE TITLE
NoSuchMethodError: 'org.bukkit.NamespacedKey org.bukkit.potion.PotionEffectType.getKey()'

### ISSUE THREAD

**Issue by SrBedrock** [TheNewEconomy/PhantomWorlds#4]
```
[00:25:02 INFO]: [PhantomWorlds] Enabling PhantomWorlds v2.07
[00:25:02 INFO]: [PhantomWorlds] Checking compatibility with server...
[00:25:02 INFO]: [PhantomWorlds] Checking for backup directory...
[00:25:02 INFO]: [PhantomWorlds] Loading files...
[00:25:02 INFO]: [PhantomWorlds] Loading file SETTINGS...
[00:25:02 INFO]: [PhantomWorlds] Loading file ADVANCED_SETTINGS...
[00:25:02 INFO]: [PhantomWorlds] Loading file MESSAGES...
[00:25:02 INFO]: [PhantomWorlds] Loading file DATA...
[00:25:02 INFO]: [PhantomWorlds] Registering commands...
[00:25:02 ERROR]: Error occurred while enabling PhantomWorlds v2.07 (Is it up to date?)
java.lang.NoSuchMethodError: 'org.bukkit.NamespacedKey org.bukkit.potion.PotionEffectType.getKey()'
        at me.lokka30.phantomworlds.commandsredux.params.PotionEffectParameter.<clinit>(PotionEffectParameter.java:44) ~[?:?]
        at me.lokka30.phantomworlds.PhantomWorlds.registerCommands(PhantomWorlds.java:238) ~[?:?]
        at me.lokka30.phantomworlds.PhantomWorlds.onEnable(PhantomWorlds.java:131) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:320) ~[server.jar:git-SportPaper-83856ad-P.49de7ec-SP.4f93526-CB.e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [server.jar:git-SportPaper-83856ad-P.49de7ec-SP.4f93526-CB.e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:409) [server.jar:git-SportPaper-83856ad-P.49de7ec-SP.4f93526-CB.e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:305) [server.jar:git-SportPaper-83856ad-P.49de7ec-SP.4f93526-CB.e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:264) [server.jar:git-SportPaper-83856ad-P.49de7ec-SP.4f93526-CB.e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:219) [server.jar:git-SportPaper-83856ad-P.49de7ec-SP.4f93526-CB.e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:667) [server.jar:git-SportPaper-83856ad-P.49de7ec-SP.4f93526-CB.e1ebe52]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[00:25:02 INFO]: [PhantomWorlds] Disabling PhantomWorlds v2.07
[00:25:02 INFO]: [PhantomWorlds] Shut-down complete (took 7084000000ms)
```

**Comment by creatorfromhell** [comment]
What is your data.yml file?

**Comment by SrBedrock** [comment]
```yaml
# .___  _                     .                     .       __               .        _
# /   \ /        ___  , __   _/_     __.  , _ , _   /       |    __.  .___   |     ___/   ____
# |,_-' |,---.  /   ` |'  `.  |    .'   \ |' `|' `. |       |  .'   \ /   \  |    /   |  (
# |     |'   ` |    | |    |  |    |    | |   |   | |  /\   /  |    | |   '  |   ,'   |  `--.
# /     /    | `.__/| /    |  \__/  `._.' /   '   / |,'  \,'    `._.' /     /\__ `___,' \___.'

worlds-to-load:

# Do not touch anything here unless you know what you are doing.
advanced:
  file-version: 2
  generated-with: '${project.version}'
```

**Comment by SrBedrock** [comment]
[PhantomWorlds 2.0.7](https://www.spigotmc.org/resources/phantomworlds.84099/update?update=535046)

**Comment by creatorfromhell** [comment]
> [PhantomWorlds 2.0.7](https://www.spigotmc.org/resources/phantomworlds.84099/update?update=535046)

not the phantomworlds, version.... The version of spigot/minecraft.

**Comment by SrBedrock** [comment]
Implementing API version 1.8.8-R0.1-SNAPSHOT

**Comment by creatorfromhell** [comment]
[PhantomWorlds-2.0.8.zip](https://github.com/TheNewEconomy/PhantomWorlds/files/14462410/PhantomWorlds-2.0.8.zip)


> Implementing API version 1.8.8-R0.1-SNAPSHOT

try this one.

**Comment by creatorfromhell** [comment]
Tested locally, and fixed with latest release.
