### ISSUE TITLE
unable to load worlds

### ISSUE THREAD

**Issue by dan28000** [TheNewEconomy/PhantomWorlds#6]
when using paper flag to move server.properties from default location while having custom default name of worlds it causes this error to ocure
due to having hardcoded server properties path here

https://github.com/TheNewEconomy/PhantomWorlds/blob/d571152fa6be21bb02c73c8c89e3e634bfc05025/src/main/java/me/lokka30/phantomworlds/misc/Utils.java#L459

```
[12:19:46] [Server thread/ERROR]: Could not pass event WorldInitEvent to PhantomWorlds v2.0.12
java.lang.NullPointerException: Cannot invoke "String.length()" because "prefix" is null
	at java.base/java.lang.String.startsWith(String.java:2285) ~[?:?]
	at java.base/java.lang.String.startsWith(String.java:2327) ~[?:?]
	at PhantomWorlds-2.0.12.jar/me.lokka30.phantomworlds.managers.WorldManager.loadManagedWorlds(WorldManager.java:66) ~[PhantomWorlds-2.0.12.jar:?]
	at PhantomWorlds-2.0.12.jar/me.lokka30.phantomworlds.PhantomWorlds.loadWorlds(PhantomWorlds.java:242) ~[PhantomWorlds-2.0.12.jar:?]
	at PhantomWorlds-2.0.12.jar/me.lokka30.phantomworlds.listeners.world.WorldInitListener.onInit(WorldInitListener.java:45) ~[PhantomWorlds-2.0.12.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor36.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[basiclandmc-api-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72) ~[basiclandmc-api-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:60) ~[basiclandmc-1.21.1.jar:1.21.1-DEV-d08a3cb]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[basiclandmc-1.21.1.jar:1.21.1-DEV-d08a3cb]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[basiclandmc-api-1.21.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:773) ~[basiclandmc-1.21.1.jar:1.21.1-DEV-d08a3cb]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:724) ~[basiclandmc-1.21.1.jar:1.21.1-DEV-d08a3cb]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[basiclandmc-1.21.1.jar:1.21.1-DEV-d08a3cb]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:374) ~[basiclandmc-1.21.1.jar:1.21.1-DEV-d08a3cb]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[basiclandmc-1.21.1.jar:1.21.1-DEV-d08a3cb]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[basiclandmc-1.21.1.jar:1.21.1-DEV-d08a3cb]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by creatorfromhell** [comment]
> when using bukkit flag to move server.properties from default location while having custom default name of worlds it causes this error to ocure (the flag has been there since at least 1.8) due to having hardcoded server properties path here
> 
> [PhantomWorlds/src/main/java/me/lokka30/phantomworlds/misc/Utils.java](https://github.com/TheNewEconomy/PhantomWorlds/blob/d571152fa6be21bb02c73c8c89e3e634bfc05025/src/main/java/me/lokka30/phantomworlds/misc/Utils.java#L459)
> 
> Line 459 in [d571152](/TheNewEconomy/PhantomWorlds/commit/d571152fa6be21bb02c73c8c89e3e634bfc05025)
> 
>  try(final InputStream input = Files.newInputStream(new File(PhantomWorlds.instance().getDataFolder(), "../../server.properties").toPath())) { 
> ```
> [12:19:46] [Server thread/ERROR]: Could not pass event WorldInitEvent to PhantomWorlds v2.0.12
> java.lang.NullPointerException: Cannot invoke "String.length()" because "prefix" is null
> 	at java.base/java.lang.String.startsWith(String.java:2285) ~[?:?]
> 	at java.base/java.lang.String.startsWith(String.java:2327) ~[?:?]
> 	at PhantomWorlds-2.0.12.jar/me.lokka30.phantomworlds.managers.WorldManager.loadManagedWorlds(WorldManager.java:66) ~[PhantomWorlds-2.0.12.jar:?]
> 	at PhantomWorlds-2.0.12.jar/me.lokka30.phantomworlds.PhantomWorlds.loadWorlds(PhantomWorlds.java:242) ~[PhantomWorlds-2.0.12.jar:?]
> 	at PhantomWorlds-2.0.12.jar/me.lokka30.phantomworlds.listeners.world.WorldInitListener.onInit(WorldInitListener.java:45) ~[PhantomWorlds-2.0.12.jar:?]
> 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor36.execute(Unknown Source) ~[?:?]
> 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[basiclandmc-api-1.21.1-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72) ~[basiclandmc-api-1.21.1-R0.1-SNAPSHOT.jar:?]
> 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:60) ~[basiclandmc-1.21.1.jar:1.21.1-DEV-d08a3cb]
> 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[basiclandmc-1.21.1.jar:1.21.1-DEV-d08a3cb]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[basiclandmc-api-1.21.1-R0.1-SNAPSHOT.jar:?]
> 	at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:773) ~[basiclandmc-1.21.1.jar:1.21.1-DEV-d08a3cb]
> 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:724) ~[basiclandmc-1.21.1.jar:1.21.1-DEV-d08a3cb]
> 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[basiclandmc-1.21.1.jar:1.21.1-DEV-d08a3cb]
> 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:374) ~[basiclandmc-1.21.1.jar:1.21.1-DEV-d08a3cb]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[basiclandmc-1.21.1.jar:1.21.1-DEV-d08a3cb]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[basiclandmc-1.21.1.jar:1.21.1-DEV-d08a3cb]
> 	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
> ```

Do you have the specfic flag you used?

**Comment by dan28000** [comment]
example would be something like where server properties would be moved to `./config/` folder
`-jar server.jar -c="config/server.properties"`
